### ISSUE TITLE
endpaginate tag is deprecated

### ISSUE THREAD

**Issue by jimmylorunning** [70kft/craft-instablog#2]
Got this message in Craft 2.5.2752: "The {% endpaginate %} tag is no longer necessary. You can remove it from your ‘blog’ template on line 11."

**Comment by jpwdesigns** [comment]
Thanks Jimmy

**Comment by jpwdesigns** [comment]
Fixed in https://github.com/70kft/craft-instablog/commit/68b9c0c715ea566dab4c90954b12278278a3b45e
@jimmylorunning you'll need to remove the endpaginate tags manually from your templates if you already have instablog installed since the fix effects the templates in the plugin folder which get copied to your site's template folder.
